language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install psycopg2
services:
  - postgresql
before_script:
  - psql -c 'create database defibs;' -U postgres
  - export DATABASE_URL=postgresql://postgres@localhost/defibs
script:
  - coverage run --source="." manage.py test
after_success:
  - coveralls
