# Generated by Django 2.0.1 on 2018-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defibs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defib',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defib',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
