# Generated by Django 2.0.1 on 2018-01-09 15:43

import defibs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defibs', '0002_auto_20180108_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='defib',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=defibs.models.RandomFileName('uploads/')),
        ),
    ]
