# Generated by Django 2.0.1 on 2018-01-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('defibs', '0003_defib_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='defib',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributors.Contributor'),
        ),
    ]
